### ISSUE TITLE
OW2 Hang on Reflex activation

### ISSUE THREAD

**Issue by QuentaceQ** [ishitatsuyuki/latencyflex2#2]
### LFX2 commit

cf29da0

### DXVK commit

a63e6d5

### NVAPI commit

6d52f03

### Game

Overwatch 2

### Issue Description

The issue i had originally was when enabling reflex it would hangs the game for a few seconds then i would get a blackscreen with only the game cursor visible(i can move it) and the game sounds still works.
After a few try i was able to launch the game with reflex enabled.
But disabling/enabling the option in game (firing range can easily repro) will make the game hang with a still picture of the game and with sound working. The game will recover a minute after and bring you back to the title screen.
It can also crash the DE and recover.

I added in the Lutris log(search the word game in the txt) the moment i started the game, the moment it crashed and when it recovered.  (i was able to compare it with a journalctl -b -f log)
I didn't edit the others, but the start/crash/recover can also be "timed" with the DXVK-nvapi log based on reflex disabling/enabling 

[lutris.log](https://github.com/ishitatsuyuki/latencyflex2/files/10384437/lutris.log)
[Overwatch_d3d11.log](https://github.com/ishitatsuyuki/latencyflex2/files/10384443/Overwatch_d3d11.log)
[dxvk-nvapi.log](https://github.com/ishitatsuyuki/latencyflex2/files/10384444/dxvk-nvapi.log)

**Comment by ishitatsuyuki** [comment]
Thanks for the report. Could you launch the game directly (Overwatch.exe in `_retail_`) and add the Lutris log from that? This would include LFX’s log about sleeping.

Just to be sure, you did the winevulkan binary patch, right?

**Comment by QuentaceQ** [comment]
Yes i did, i edited the file with an hex editor. 
sorry about the status of the issue i misclicked.

[lutris.log](https://github.com/ishitatsuyuki/latencyflex2/files/10384643/lutris.log)

**Comment by ishitatsuyuki** [comment]
Should be fixed now, please rebuild the core module from master and copy it.

> It can also crash the DE and recover.

I did not reproduce this, and I don't have any idea right now what can cause this. If it happens again please let me know.

**Comment by QuentaceQ** [comment]
Works fine now! (at least during my short testing)
Thanks.
I'll try to play with the settings and see if it happens in other situations.
