### ISSUE TITLE
LFX2 with DXVK Async

### ISSUE THREAD

**Issue by NogradThGin** [ishitatsuyuki/latencyflex2#3]
Hello,

More than an issue, it's more like a question.
Is it possible to patch [DXVK-Async](https://gitlab.com/Ph42oN/dxvk-gplasync/) (GPL+Async) with your modification from [DXVK LFX 2.0](https://github.com/ishitatsuyuki/dxvk/tree/lfx2 )?
To provide both LatencyFleX 2.0 and DXVK Async ?

Currently using LFX 2.0 due to the fact I can't (maybe I miss something) use LFX 1.0 on Apex Legends.

Not sure if [MangoHud](https://github.com/ishitatsuyuki/MangoHud) still support the `graph_latency` custom parameter ?

Thanks by advance, and for the hard work!

**Comment by ishitatsuyuki** [comment]
DXVK-Async is not supported.
