### ISSUE TITLE
Currently crashing for Apex Legends

### ISSUE THREAD

**Issue by Zeioth** [ishitatsuyuki/latencyflex2#4]
### LFX2 commit

https://github.com/ishitatsuyuki/latencyflex2/commit/80d86b4d868d2720ec586f35127dc8cc14534f3c

### DXVK commit

https://github.com/ishitatsuyuki/dxvk/commit/824dda7c6060960bdf1119d2f4e8c1b98f7b6c69

### NVAPI commit

https://github.com/ishitatsuyuki/dxvk-nvapi/commit/2631f7e5d32be017306937f71c846ffdee73e8fc

### VKD3D-Proton commit

https://github.com/ishitatsuyuki/vkd3d-proton/commit/782fe94eb684a760e68e781af7bd941ef8772a02

### Game

Apex Legends

### Issue Description

Apex Legends crashes on startup when running with LatencyFlex2. I get to see Apex loading screen, but the game inmediatelly freezes.

## How did I install LatencyFlex2
I installed LatencyReflex2 by following the webpage instructions (reproducible script [here](https://github.com/Zeioth/LatencyFlex2-installer))

## Why should it work
Running

```
ls -l ~/.steam/steam/steamapps/compatdata/1172470/pfx/drive_c/windows/system32/ | grep latencyflex2_rust.dll
ls -l ~/.steam/steam/steamapps/common/"Proton - Experimental"/files/lib64/wine/dxvk
ls -l ~/.steam/steam/steamapps/common/"Proton - Experimental"/files/lib64/wine/nvapi
ls -l ~/.steam/steam/steamapps/common/"Proton - Experimental"/files/lib64/wine/vkd3d-proton
```
Thows 
```
.r-xr-xr-x zeioth zeioth 964 KB Thu Apr 13 06:04:34 2023  d3d10core.dll
.r-xr-xr-x zeioth zeioth 3.5 MB Thu Apr 13 06:04:34 2023  d3d11.dll
.r-xr-xr-x zeioth zeioth 3.1 MB Thu Apr 13 06:04:34 2023  d3d9.dll
.r-xr-xr-x zeioth zeioth 2.4 MB Thu Apr 13 06:04:34 2023  dxgi.dll
.r-xr-xr-x zeioth zeioth 806 KB Fri Mar 10 19:39:46 2023  openvr_api_dxvk.dll
.r-xr-xr-x zeioth zeioth  67 B  Sun Apr  2 10:12:42 2023  version
.r-xr-xr-x zeioth zeioth 1.4 MB Thu Apr 13 06:04:34 2023  nvapi64.dll
.r-xr-xr-x zeioth zeioth  74 B  Sun Apr  2 10:12:42 2023  version
.r-xr-xr-x zeioth zeioth 2.8 MB Thu Apr 13 06:04:34 2023  d3d12.dll
.r-xr-xr-x zeioth zeioth 2.5 MB Sun Apr  2 10:12:42 2023  d3d12core.dll
.r-xr-xr-x zeioth zeioth  82 B  Sun Apr  2 10:12:42 2023  version
```
Showing all the necessary files were created at 06:04 without errors. So the necessary files are there.

Then I ran Apex Legends with the parameters:

```
PROTON_ENABLE_NVAPI=1 DXVK_NVAPI_ALLOW_OTHER_DRIVERS=1 DXVK_NVAPI_USE_LATENCY_MARKERS=0 DXVK_NVAPI_DRIVER_VERSION=49729 DXVK_CONFIG_FILE=~/.local/share/latency-flex/dxvk.conf DXVK_NVAPI_LOG_LEVEL=info DXVK_NVAPI_LOG_PATH=~/.local/share/latency-flex DXVK_FILTER_DEVICE_NAME="AMD Radeon RX 6700 XT" %command% -dev -novid
```
The game crashes. The dxvk-nvapi.log show this:

```
---------- 2023-04-13 06:07:03 ----------
NvAPI_QueryInterface (0xad298d3f): Unknown function ID
DXVK-NVAPI lfx2-v2.0.0-alpha.2 (r5apex.exe)
Successfully acquired Vulkan vkGetInstanceProcAddr @ 0x3b6dc40a0
DXVK_NVAPI_ALLOW_OTHER_DRIVERS is set, reporting also GPUs with non-NVIDIA proprietary driver
NvAPI Device: AMD Radeon RX 6700 XT (RADV NAVI22) (23.0.2)
NvAPI Output: \\.\DISPLAY1
NvAPI Output: \\.\DISPLAY2
NvAPI Output: \\.\DISPLAY3
NvAPI Output: \\.\DISPLAY4
NvAPI Output: \\.\DISPLAY5
NvAPI Output: \\.\DISPLAY6
DXVK_NVAPI_DRIVER_VERSION is set to '49729', reporting driver version 497.29
NvAPI_Initialize: OK
NvAPI_QueryInterface (0x33c7358c): Unknown function ID
NvAPI_QueryInterface (0x593e8644): Unknown function ID
NvAPI_D3D_SetSleepMode (Disabled): OK
```

Might this be a DXVK-NVAPI error? I've been through some of the commits and I see LatencyFlex2 DXVK says WIP, so maybe it is expected to fail at this point.

**Comment by ishitatsuyuki** [comment]
Please attach your `PROTON_LOG`.

**Comment by Zeioth** [comment]
Sure thing, [here](https://pastebin.com/raw/kuTDt6rN).

**Comment by ishitatsuyuki** [comment]
Can you double check your listed commits matches what you built? Your log says `DXVK-NVAPI lfx2-v2.0.0-alpha.2 (r5apex.exe)`, but your issue description points to a tip of branch commit.

I also just noticed I mistagged the buggy version of nvapi for `lfx2-v2.0.0-alpha.2`. I've now overwritten the tag with the working version, so if that's the case you need to git fetch and checkout again.

**Comment by Zeioth** [comment]
Yes I'm not sure about the commits sorry. I cloned all projects as described in [LatencyFlex2 instructions.](https://lfx2.ishitatsuy.uk/shim/building.html)

```
git clone https://github.com/ishitatsuyuki/latencyflex2.git -b v2.0.0-alpha.2
git clone --recursive https://github.com/ishitatsuyuki/dxvk.git -b lfx2-v2.0.0-alpha.2
git clone --recursive https://github.com/ishitatsuyuki/dxvk-nvapi.git -b lfx2-v2.0.0-alpha.2
git clone --recursive https://github.com/ishitatsuyuki/vkd3d-proton.git -b lfx2-v2.0.0-alpha.2
```

Thank you for checking, I'm gonna reinstall "nvapi" and try again.

**Comment by Zeioth** [comment]
This time I've checked the latest commits pulled by the commands of my last post:
```
LatencyFlex2 core:
commit 80d86b4d868d2720ec586f35127dc8cc14534f3c (HEAD, tag: v2.0.0-alpha.2, origin/master, origin/HEAD)
Author: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
Date:   Tue Mar 21 13:57:55 2023 +0900

    Update install instructions to use versioned tags

dxvk:
commit a9aa976c6370bb651bd35d6cc79dd88b5abee562 (HEAD, tag: lfx2-v2.0.0-alpha.2)
Author: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
Date:   Tue Mar 21 22:25:46 2023 +0900

    Fix crashing on disabling Reflex

dxvk-nvapi: 
commit a9aa976c6370bb651bd35d6cc79dd88b5abee562 (HEAD, tag: lfx2-v2.0.0-alpha.2)
Author: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
Date:   Tue Mar 21 22:25:46 2023 +0900

    Fix crashing on disabling Reflex

vkd3d-proton:
commit 782fe94eb684a760e68e781af7bd941ef8772a02 (HEAD, tag: lfx2-v2.0.0-alpha.2, origin/lfx2)
Author: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
Date:   Sun Jan 8 19:10:34 2023 +0900

    Convert to new unified ID3DLfx2ExtDevice API
    
    Signed-off-by: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
```

After reinstalling, I get this [dxvk-nvapi.log](https://pastebin.com/raw/qANLd0RM) and this [proton log (steam-1172470.log)](https://pastebin.com/raw/esnUCtXe). Seems like the same issue.

**Comment by ishitatsuyuki** [comment]
You need to run `git fetch --tags`.

**Comment by ishitatsuyuki** [comment]
Nevermind, your dxvk-nvapi commits seems correct. Let me recheck what might be wrong.

**Comment by Zeioth** [comment]
I realized after cloning the projects, I was compiling them as in the instructions provided:

    ./package-release.sh master ./target

But we should use our branch instead right?

    ./dxvk-nvapi/package-release.sh lfx2-v2.0.0-alpha.2 ./target --no-package
    ./dxvk-nvapi/package-release.sh lfx2-v2.0.0-alpha.2 ./target
    ./vkd3d-proton/package-release.sh lfx2-v2.0.0-alpha.2 ./target --no-package

I tried this but the error and the logs are the same: [nvapi log](https://pastebin.com/raw/NiLtWaC4), [proton log](https://pastebin.com/raw/J2Bzs13B)

**Comment by Zeioth** [comment]
I recorded a [video showing the installation process ](https://www.youtube.com/watch?v=cL__MBWOdgM). Also, [nvapi log](https://pastebin.com/raw/KgbxmKyh), [proton log](https://pastebin.com/raw/MiMxzqHG)

**Comment by ishitatsuyuki** [comment]
Should be fixed with https://github.com/ishitatsuyuki/dxvk-nvapi/commit/30e6b0046c469fd998537ae889aa181dc61b9143. You can cherry pick the commit or just checkout it and rebuild.

**Comment by Zeioth** [comment]
Right on the spot!! I manually patched '/dxvk-nvapi/src/d3d/lfx2.cpp' with that and Apex launches now.

![screenshot_2023-04-13_18-26-04_033824174](https://user-images.githubusercontent.com/3357792/231824286-1f9c998a-2fe6-48e3-9af5-d500211cf1f5.png)

The patch is safe to push to head. Reflex can now be enabled inside the game. After doing so the logs show 

    NvAPI_D3D_SetSleepMode (Enabled/0us): OK

Meaning everything works as expected.

**Comment by ishitatsuyuki** [comment]
Good to hear it works, I'll retag nvapi then. (Ideally I shouldn't be overwriting tags, but there's no update for other components at this time so retagging seems easier)

**Comment by Zeioth** [comment]
Just one question: dxvk-nvapi. log doesn't show 

    NvAPI_D3D_SetLatencyMarker: OK

But reflex seems to work ok. There is any reason to not just always set DXVK_NVAPI_USE_LATENCY_MARKERS=1?

**Comment by ishitatsuyuki** [comment]
You set `DXVK_NVAPI_USE_LATENCY_MARKERS=0` exactly because the game doesn't support latency markers. We cannot know this information without launching the game and observing its behavior hence it's a manual configuration option.
